### ISSUE TITLE
Can't authenticate with old electron version

### ISSUE THREAD

**Issue by FabrizioCongia** [Kiina/MMM-trakt#17]
Hi, I can't authenticate with electron 2.0.4. I tried to delete tocken.js and didn't solve the issue. I saw in other closed issues that electron should be updated in order to solve similar problems, but I have a Raspberry 1 and newer electron versions are not available for arm6 architecture. should I give up? Here's the log:
```0|mm       | (node:678) UnhandledPromiseRejectionWarning: Error: OAuth required
0|mm       |     at Trakt._call (/home/pi/MagicMirror/modules/MMM-trakt/node_modules/trakt.tv/trakt.js:195:122)
0|mm       |     at Object.tmp.(anonymous function) [as shows] (/home/pi/MagicMirror/modules/MMM-trakt/node_modules/trakt.tv/trakt.js:49:33)
0|mm       |     at trakt.import_token.then.newTokens (/home/pi/MagicMirror/modules/MMM-trakt/node_helper.js:55:32)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|mm       | (node:678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch() (rejection id: 1)
0|mm       | (node:678) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Kiina** [comment]
Electron 2 should work, the other issue only affected electron 1.x versions iirc. Which version of MagicMirror are you currently using?

**Comment by FabrizioCongia** [comment]
Should be MM 2.7.1. Installed yesterday for the first time

**Comment by Kiina** [comment]
Is it the full log? Seems like it's missing a line on top? Just tried latest MM with electron downgraded to 2.0.4 and couldn't reproduce. Maybe if there is more to the log I can try to resolve it

**Comment by FabrizioCongia** [comment]
The first line is `(node:678)UnhandledPromiseRejectionWarning: Error: OAuth required`. 
I have other errors that i suppose are unrelated since they are flagged as different nodes (font missing, unable to create cache). 
Magic Mirror is working as is supposed to do but MMM-trakt just types "Error loading module. Please check the logs".

**Comment by kominoshja** [comment]
I have the same error message with v3.0.13 of Electron
