### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Hoaxr** [Kiina/MMM-trakt#24]
I hope someone is also using this module and maybe has a solution.
It worked before but for the last months it stopt working.
I disabled the module hoping it would be solved in the future, but still the same problem.

Error message: Error loading module. Please check the logs.

[21.02.2022 10:42.50.572] [ERROR] (node:34) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad Request)
    at EventEmitter.<anonymous> (/opt/magic_mirror/modules/MMM-trakt/node_modules/trakt.tv/node_modules/got/dist/source/as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
[21.02.2022 10:42.50.573] [ERROR] (node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[21.02.2022 10:42.50.574] [ERROR] (node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Hoaxr** [comment]
Seems the added some new options on the api that i had to check on. Now it works again
